# Generated by Django 5.2.16 on 2026-07-09 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('order.confirmed', 'Order confirmed'), ('payment.failed', 'Payment failed'), ('order.shipped', 'Order shipped'), ('order.delivered', 'Order delivered'), ('order.cancelled', 'Order cancelled'), ('tryon.completed', 'Try-on ready'), ('tryon.failed', 'Try-on failed'), ('csr.created', 'Stylist request'), ('csr.contacted', 'Stylist contacted'), ('csr.resolved', 'Stylist resolved')], max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='notificatio_user_id_554261_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='unique_notification_dedupe_per_user')],
            },
        ),
    ]
