# Generated by Django 5.2.16 on 2026-07-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_indexes_idempotency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_0ae59f_idx',
            old_name='orders_orde_user_id_6b3f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_c6dd84_idx',
            old_name='orders_orde_status_f8c8c1_idx',
        ),
    ]
